version: '3'

services:

  web:
    container_name: "notify_nginx"
    build: ./nginx
    restart: on-failure
    depends_on:
      - fast_api
    ports:
      - "80:80"

  fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"