version: '3'

services:

  web:
    build: ./nginx
    container_name: "notify_nginx"
    depends_on:
      - fast_api
    ports:
      - "8082:80"
    networks:
      - custom

  fast_api:
    container_name: "notify_fast_api"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - custom

  mongodb:
    container_name: "notify_mongo"
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - custom

networks:
  custom:
    driver: bridge